[package]
name = "websocket-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "tls"] }
warp = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.23"
futures-util = "0.3"
serde_json = "1.0"
uuid = { version = "1.10", features = ["v4"] }
